[package]
name = "hellas-consensus"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["ember arlynx <ember@hellas.ai>"]

[dependencies]
muchin = { path = "../muchin" }
serde = { version = "1.0", features = ["derive"] }