[package]
name = "hellas-morpheus"
version = "0.1.0"
edition = "2024"

[dependencies]
hints = { path = "../hints" }
redb = "2.6"
fastbloom = { version = "0.12", features = ["serde", "rand"] }
blake3 = "1.8"
ron = "0.10"

derivative = "2.2"
tracing = "0.1"

ark-std = "0.5.0"
ark-serialize = { version = "0.5.0", features = ["serde_with"] }
ark-serialize-derive = { version = "0.5.0" }

serde = { version = "1.0", features = ["derive", "rc"] }
serde_with = "3"
serde_json_any_key = "2"
postcard = { version = "1.1", features = ["use-std"] }

time = { version = "0.3.39", features = ["serde"] }
test-log = { version = "0.2", features = ["trace"] }

derive_more = { version = "2", features = ["debug"] }


[dev-dependencies]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
