[package]
name = "hellas-morpheus"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = "0.1"
time = { version = "0.3.39", features = ["serde"] }